# Archivo: docker-compose.yml

services:
  # Servicio para nuestra API
  api:
    build:
      context: ./
    restart: always
    environment:
      - DB_HOST=postgres-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=5432
      - API_PORT=4000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      # AHORA DEPENDE DEL ESTADO DE SALUD DEL SERVICIO
      postgres-db:
        condition: service_healthy

  # Servicio para nuestra base de datos PostgreSQL
  postgres-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # --- AÑADIR ESTA SECCIÓN COMPLETA ---
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    # --- FIN DE LA SECCIÓN AÑADIDA ---

  # NUEVO SERVICIO: Panel de Administración
  admin-panel:
    # Construimos desde el otro repositorio de GitHub
    build:
      context: https://github.com/Gastaire/distribuidora-admin-panel.git
    restart: always

volumes:
  postgres-data:
    driver: local

